language: python

python:
    - 3.3
    - 3.4
    - pypy

install:
 - python setup.py sdist
 - mkdir tmp
 - tar xvf dist/booby-*.tar.gz -C tmp
 - python tmp/booby-*/setup.py install

 - pip install -r test-requirements.txt

script:
 - nosetests -P tests/unit
 - nosetests -P tests/integration
